# Generated by Django 6.0.2 on 2026-02-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_months', models.IntegerField()),
                ('muac_mm', models.IntegerField()),
                ('edema', models.IntegerField(default=0)),
                ('appetite', models.CharField(max_length=20)),
                ('danger_signs', models.IntegerField(default=0)),
                ('muac_z_score', models.FloatField(blank=True, null=True)),
                ('clinical_status', models.CharField(blank=True, max_length=20, null=True)),
                ('recommended_pathway', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
