# Generated by Django 6.0.2 on 2026-02-13 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-assessment_date']},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_facility',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='chw_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['chw_username', '-assessment_date'], name='assessments_chw_use_cdaebe_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['child_id'], name='assessments_child_i_ab51c9_idx'),
        ),
    ]
