# Generated by Django 6.0.2 on 2026-02-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='doctor_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
