# Generated by Django 6.0.2 on 2026-02-11 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_months', models.IntegerField()),
                ('muac_mm', models.IntegerField()),
                ('muac_z_score', models.FloatField(blank=True, null=True)),
                ('edema', models.IntegerField(default=0)),
                ('appetite', models.CharField(choices=[('good', 'Good'), ('poor', 'Poor'), ('failed', 'Failed')], max_length=10)),
                ('danger_signs', models.IntegerField(default=0)),
                ('clinical_status', models.CharField(blank=True, choices=[('SAM', 'Severe Acute Malnutrition'), ('MAM', 'Moderate Acute Malnutrition'), ('Healthy', 'Healthy')], max_length=20)),
                ('recommended_pathway', models.CharField(blank=True, choices=[('SC_ITP', 'Stabilization Centre / Inpatient'), ('OTP', 'Outpatient Therapeutic Programme'), ('TSFP', 'Targeted Supplementary Feeding Programme'), ('None', 'No Treatment Required')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('chw_name', models.CharField(blank=True, max_length=200)),
                ('chw_phone', models.CharField(blank=True, max_length=20)),
                ('chw_notes', models.TextField(blank=True)),
                ('chw_signature', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('chw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='accounts.facility')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ADMITTED', 'Admitted'), ('IN_TREATMENT', 'In Treatment'), ('RECOVERED', 'Recovered'), ('DEFAULTED', 'Defaulted'), ('DIED', 'Died'), ('TRANSFERRED', 'Transferred')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_records', to='assessments.assessment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['timestamp'], name='assessments_timesta_6829d3_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['state'], name='assessments_state_28ebcb_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['facility'], name='assessments_facilit_d261c5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['clinical_status'], name='assessments_clinica_27906d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['child_id'], name='assessments_child_i_21526a_idx'),
        ),
    ]
