# Generated by Django 6.0.2 on 2026-03-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chwuser',
            name='role',
            field=models.CharField(choices=[('MOH_ADMIN', 'MoH Administrator'), ('CHW', 'Community Health Worker'), ('DOCTOR', 'Doctor')], default='CHW', max_length=20),
        ),
    ]
