# Generated by Django 6.0.2 on 2026-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_chwuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chwuser',
            name='doctor_description',
            field=models.TextField(blank=True, help_text='Brief description of expertise and experience'),
        ),
        migrations.AddField(
            model_name='chwuser',
            name='doctor_specialization',
            field=models.CharField(blank=True, help_text='e.g., Child Nutrition Specialist, Emergency Medicine', max_length=200),
        ),
        migrations.AddField(
            model_name='chwuser',
            name='doctor_title',
            field=models.CharField(blank=True, help_text='e.g., Pediatrician, General Practitioner', max_length=100),
        ),
        migrations.AddField(
            model_name='chwuser',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of medical experience', null=True),
        ),
    ]
